"""empty message

Revision ID: 0036b32b475f
Revises: b7caea266b03
Create Date: 2023-07-05 13:42:17.594031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0036b32b475f'
down_revision = 'b7caea266b03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_col', sa.Boolean(), nullable=False))
        batch_op.alter_column('content_bottom',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=250),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('content_top',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=250),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.alter_column('content_top',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('content_bottom',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.drop_column('test_col')

    # ### end Alembic commands ###
