"""empty message

Revision ID: 67ec779f9643
Revises: 6d6fb7e254a6
Create Date: 2023-07-05 12:14:57.196925

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67ec779f9643'
down_revision = '6d6fb7e254a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posteed', sa.DateTime(), nullable=False))
        batch_op.drop_column('date_posted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.drop_column('date_posteed')

    # ### end Alembic commands ###
