"""empty message

Revision ID: 6d6fb7e254a6
Revises: 46d616288b0f
Create Date: 2023-07-05 12:13:00.706560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d6fb7e254a6'
down_revision = '46d616288b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_top', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('content_bottom', sa.String(length=200), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('content_bottom')
        batch_op.drop_column('content_top')

    # ### end Alembic commands ###
