"""empty message

Revision ID: 75a63cb6cf67
Revises: a8d906d04ad1
Create Date: 2023-07-05 13:20:47.188136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a63cb6cf67'
down_revision = 'a8d906d04ad1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.alter_column('content_bottom',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=250),
               nullable=False)
        batch_op.alter_column('content_top',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=250),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.alter_column('content_top',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('content_bottom',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
