"""empty message

Revision ID: 7c7d8949ed9e
Revises: cafe988d9c5f
Create Date: 2023-07-05 13:12:25.581037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7d8949ed9e'
down_revision = 'cafe988d9c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.alter_column('content_top',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('content_bottom',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.alter_column('content_bottom',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('content_top',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
