"""empty message

Revision ID: 92f7123c3082
Revises: 0036b32b475f
Create Date: 2023-07-05 13:46:59.085142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f7123c3082'
down_revision = '0036b32b475f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.alter_column('content_bottom',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=250),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('content_top',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=250),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.alter_column('content_top',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('content_bottom',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))

    # ### end Alembic commands ###
