"""empty message

Revision ID: b7caea266b03
Revises: c07e1906efb6
Create Date: 2023-07-05 13:32:57.477795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7caea266b03'
down_revision = 'c07e1906efb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.drop_column('content_top')
        batch_op.drop_column('content_bottom')
 
        batch_op.add_column(sa.Column('content_top', sa.String(length=200), nullable=False, server_default='This is crazy'))
        batch_op.add_column(sa.Column('content_bottom', sa.String(length=200), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meme', schema=None) as batch_op:
        batch_op.alter_column('content_top',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('content_bottom',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
